// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9z8b1bcKItQh_m8UywhZ6hPj6Y5DrYTg',
    appId: '1:964290414172:web:36982194400b0f42ea0899',
    messagingSenderId: '964290414172',
    projectId: 'aventuraflutter',
    authDomain: 'aventuraflutter.firebaseapp.com',
    databaseURL: 'https://aventuraflutter-default-rtdb.firebaseio.com',
    storageBucket: 'aventuraflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7X-4rb-cSrToHvGHgwY6nQGCrOZlcwM',
    appId: '1:964290414172:android:d57bc09adc0bc813ea0899',
    messagingSenderId: '964290414172',
    projectId: 'aventuraflutter',
    databaseURL: 'https://aventuraflutter-default-rtdb.firebaseio.com',
    storageBucket: 'aventuraflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrGNQXdP5iTWWR2j4B5NnrMmfQ3KdKZo',
    appId: '1:964290414172:ios:4fcd5c2238bf333aea0899',
    messagingSenderId: '964290414172',
    projectId: 'aventuraflutter',
    databaseURL: 'https://aventuraflutter-default-rtdb.firebaseio.com',
    storageBucket: 'aventuraflutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoNetflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALrGNQXdP5iTWWR2j4B5NnrMmfQ3KdKZo',
    appId: '1:964290414172:ios:4fcd5c2238bf333aea0899',
    messagingSenderId: '964290414172',
    projectId: 'aventuraflutter',
    databaseURL: 'https://aventuraflutter-default-rtdb.firebaseio.com',
    storageBucket: 'aventuraflutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoNetflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9z8b1bcKItQh_m8UywhZ6hPj6Y5DrYTg',
    appId: '1:964290414172:web:9322c24b926f2b59ea0899',
    messagingSenderId: '964290414172',
    projectId: 'aventuraflutter',
    authDomain: 'aventuraflutter.firebaseapp.com',
    databaseURL: 'https://aventuraflutter-default-rtdb.firebaseio.com',
    storageBucket: 'aventuraflutter.firebasestorage.app',
  );
}
